// apps/player-component-test/react/src/App.tsx
import './App.css'
import '@dotlottie/player-component'

declare global {
  namespace JSX {
    interface IntrinsicElements {
      'dotlottie-player': any;
    }
  }
}

function App() {
  return (
    <>
      <dotlottie-player src="https://lottie.host/53ececb8-cfb3-4505-ac42-b0214d81d2d7/UBIa29hJUQ.lottie" direction="1" controls playmode="bounce" speed={6} />
    </>
  )
}

export default App

// apps/player-component-nuxt/app.vue
<script setup lang="ts">
import { ref } from 'vue';

const speed = ref(5);
const direction = ref(1);
const playMode = ref('bounce');
</script>

<template>
  <div>
    Vue + Vite 🍒 test

    <dotlottie-player
      src="https://lottie.host/53ececb8-cfb3-4505-ac42-b0214d81d2d7/UBIa29hJUQ.lottie"
      :direction.attr="direction"
      controls
      autoplay
      :playMode.attr="playMode"
      loop
      :speed.attr="speed"
    />
  </div>
</template>
